# Change these first
owner: Savvas Tech Suport # Your GitHub organization or username
repo: k12tech-test # Your GitHub repository name

# Add your sites here
sites:
  - name: SALT
    url: https://salt.savvas.com/
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /k12-tech
  logoUrl: https://github.com/SavvasStephenPartington/k12tech-test/blob/d102276f7b10b5f2fbe2ff414137bd547a4ddd78/favicon.png
  name: Savvas K12-Tech
  introTitle: "*powered by upptime monitor and status page, powered entirely by GitHub."
  introMessage: Savvas Technical Support Uptime testing site
  navbar:
    - title: K12-Tech
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
